//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gameoverdev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        public int BLOG_ID { get; set; }
        public string BLOG_TITLE { get; set; }
        public string BLOG_TEXT { get; set; }
        public string BLOG_AUTHOR { get; set; }
    }
}
